version: "3"

services:
  postgres:
    restart: always
    image: postgres
    container_name: money-planning-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./docker/database/data/postgres:/var/lib/postgresql/data

  php-fpm:
    restart: always
    container_name: money-planning-php
    build:
      context: docker/php-fpm
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@money-planning-database:5432/${DATABASE_NAME}?serverVersion=11&charset=utf8
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/www.conf:/etc/php8/php-fpm.d/www.conf:ro
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
        - postgres

  nginx:
    restart: always
    image: nginx:alpine
    container_name: money-planning-nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
      - "443:443"
      - "3001:3001"
    links:
      - php-fpm
